export const API = {
    SIGNUP:process.env.NEXT_PUBLIC_API_SIGNUP!,
    LOGIN:process.env.NEXT_PUBLIC_API_LOGIN!,
    FORGOT_PASSWORD:process.env.NEXT_PUBLIC_API_FORGOT_PASSWORD!,
    RESET_PASSWORD:process.env.NEXT_PUBLIC_API_RESET_PASSWORD!,
    NEW_RESERVATION:process.env.NEXT_PUBLIC_API_NEW_RESERVATION!
}